### ISSUE TITLE
Unable to get property 'jscomp_symbol_toStringTag10' of undefined or null reference

### ISSUE THREAD

**Issue by chriszrc** [es-shims/get-own-property-symbols#13]
This error is thrown here (and only in IE11, but that's also the only place the polyfill is being loaded):

```
o = e.getOwnPropertyDescriptor(r, "toString"), o.value = function () {
                            var e = i.call(this), t = this[Symbol.toStringTag];
```

Specifically, the `t = this[Symbol.toStringTag];`. The page is loading highcharts, which seems to be the library that is having trouble with this. This is part of a polymer project, in which this polyfill is part of the default export-

**Comment by ljharb** [comment]
are you using `'use strict';` and naively concatenating files together, such that this highcharts function is incorrectly being ran in strict mode?

**Comment by alienriver49** [comment]
`'use strict';` is at the top of the Highcharts library files so why is that a problem? I'll say this, I'm running into the same issue with webcomponentsjs in IE11 and they have `'use strict';` at the top of their webcomponents-bundle.js. Removing the `'use strict';` from their bundle fixes the issue, but I shouldn't have to be doing that, so there's something more going on here.

After some testing it looks like loading the core-js polyfills before webcomponentsjs fixes the issue since that applies their Symbol polyfill before webcomponentsjs polyfills Symbol using this polyfill. I think it's worth investigating and possibly taking some inspiration from their polyfill to help fix up this one.

@TimvdLippe you are a maintainer of webcomponentsjs and have done a commit to this polyfill, any thoughts?

**Comment by TimvdLippe** [comment]
@alienriver49 Sorry I am not familiar with this issue nor with the Highcharts library. If this polyfill does not work in strict mode, I think it is best to try and fix that. As far as I know, `'use strict';` is used in all modern projects now, so I would expect that we are not the only ones running into this issue.

**Comment by chriszrc** [comment]
@ljharb Yes, `'use strict';` was the issue, although I had to remove it not just from the highcharts lib, but also @TimvdLippe I had to remove it from the webcomponents-sd-ce-pf.js file as well, to get my web-component to work in IE11

**Comment by ljharb** [comment]
@TimvdLippe most polyfills run in sloppy mode and require it; a file written in one mode must never be run in a different one. Modern build processes do not naively concatenate files; they bundle modules, and do not have this problem.

**Comment by ljharb** [comment]
Sounds like this is answered.

**Comment by ljharb** [comment]
No - your choice of strict mode applies only to that file. The answer is, don’t use an archaic build process.

I can assure you that zero bunglers - webpack and rollup included - put their entire file in strict mode, as that would break a ton of code. They put each module’s *closure* in strict mode, which is fine.

**Comment by ljharb** [comment]
In other words, any tool that assumes everything is in strict mode is inherently broken. No note in the readme is required, because it would be true for the entire language.

**Comment by ljharb** [comment]
That's an unfortunate default; is there any issue filed on rollup to fix that?

**Comment by TimvdLippe** [comment]
You can disable it:
https://rollupjs.org/guide/en#output-strict-strict-no-strict-

Op vr 2 nov. 2018 om 19:53 schreef Jordan Harband <notifications@github.com

**Comment by TimvdLippe** [comment]
Apparently the Rollup maintainers arrived at a different conclusion. I personally am indifferent about it, but with recent changes to the platform like ES modules by default are strict, I don't think they made a bad choice per se. If you want to challenge their choice, I think it is best to raise an issue at https://github.com/rollup/rollup/issues
